---
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)s | %(levelname)s | %(module)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S%z"
  detailed:
    format: "%(asctime)s | %(levelname)s | %(filename)s:%(lineno)s | func:%(funcName)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S%z"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
loggers:
  root:
    level: DEBUG
    handlers:
      - console
